### PR TITLE
Use astyle(1) to make style consistent

### PR DESCRIPTION
**Pull request by smortex**
This was discussed in #53 ([link to comment](https://github.com/nfc-tools/libfreefare/pull/53#issuecomment-289039066)).

When this pull request is approved, I will, before merging I will:

  - [x] Rebase branch on top of master;
  - [x] Run `make style` and add changes to this branch.

### CODE REVIEW

**Comment by doegox** [comment]
Maybe take the chance to align style between libnfc and libfreefare?
At the moment libnfc style is:

    astyle --formatted --mode=c --suffix=none \
    --indent=spaces=2 --indent-switches --indent-preprocessor \
    --keep-one-line-blocks --max-instatement-indent=60 \
    --style=linux --pad-oper --unpad-paren --pad-header \
    --align-pointer=name {} \;

**Comment by smortex** [comment]
Huhu, in fact I conscientiously used settings that match FreeBSD's `style(9)` since it's basically what I used when writing libfreefare.

The only difference these flags produce with the current code is that I used a space before an opening parenthesis when calling a function (when I did not forget it, bad habit I took from mono's code), and it's not possible to have this exact behavior with astyle.  This leads to quite a lot of changes, but I am OK with it.  However, changing all indentation rules seems gratuitous to me.

Do you think it's better to have a similar style in libnfc and libfreefare ?

**Comment by doegox** [comment]
Not that important if it makes more trouble than benefits, forget about it

**Comment by smortex** [comment]
Fsck, committing the result of `make style` dismissed the review approval :open_mouth:

**Pull request merged**
