### PR TITLE
allow to cross-compile 32 and 64 bit dlls using MinGW

### PR DESCRIPTION
**Pull request by ChristophGr**

### CODE REVIEW

**Comment by smortex** [comment]
Hey @nfc-tools/core and @nfc-tools/contributors, any Windows user to review this PR?

**Comment by ChristophGr** [comment]
OK, I merged the two now

**Comment by smortex** [comment]
Looks good!  No contributor reported feedback for the feature itself, so I merged it.

Thanks!

**Comment by xavave** [comment]
working good in 64bits with msys2 (mingw64 shell):
`
mkdir libfreefare-build  
git clone https://github.com/nfc-tools/libfreefare.git
cd libfreefare-build 
cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ../libfreefare  -DLIBNFC_INCLUDE_DIRS=path/to/libnfc/include  -DLIBNFC_LIBRARIES=/path/to/libnfc.dll

mingw32-make  
`
and I had also to comment CmakeLists.txt, lines 41,43,44 to not force 32 bits
`# add_definitions("-m32")
  add_definitions("-DNOCRYPT")
  #set(CMAKE_SHARED_LINKER_FLAGS -m32)
  #set(CMAKE_EXE_LINKER_FLAGS -m32)`

image

cross-compiled binaries attached
[examples.zip](https://github.com/nfc-tools/libfreefare/files/4056322/examples.zip)

**Pull request merged**
